project:
  type: website
  output-dir: docs

website:
  title: "Justin Gregoire"
  open-graph:
    locale: en_US
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - calendar.qmd
      - href: dog.qmd
        text: Dog Walking
format:
  html:
    theme: flatly
    css: ['~/Documents/GitHub/justingregoire.me/resume_gen/css/custom_resume.css','~/Documents/GitHub/justingregoire.me/resume_gen/css/styles.css','resume']
    link-external-newwindow: true


