project:
  type: website
  output-dir: docs

website:
  title: "Justin Gregoire"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - calendar.qmd
      - href: dog.qmd
        text: Dog Walking

format:
  html:
    theme: flatly
    css: styles.css
    link-external-newwindow: true


