project:
  type: website

website:
  title: "justingregoire.me"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - calendar.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

execute:
  freeze: auto

