project:
  type: website
  output-dir: docs

website:
  title: "Justin Gregoire"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume_page.qmd
      - calendar.qmd

format:
  html:
    theme: flatly
    css: styles.css
    link-external-newwindow: true

execute:
  freeze: auto

